import type { Metadata } from "next";
import Header from "./components/header/Header";
import "./globals.scss";
import { robotoCondensed } from './font';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
        <body className={robotoCondensed.className}>
            <Header />
            {children}
        </body>
    </html>
  );
}
